### ISSUE TITLE
Log4j configuration not used in cassandra-unit-2.0.2.2

### ISSUE THREAD

**Issue by DoNuT1985** [jsevellec/cassandra-unit#105]
We were using 2.0.2.1 for quite extensive tests of our project's CQL layer and we've upgraded to 2.0.2.2 due to various file access errors with cassandra DB store files.

However, with the current version for some reason log4j configuration is omitted and we're getting tons of output bumping up our nightly build durations from 6-10 minute up to 1+ hour.

This can easily reproduced by cloning https://github.com/jsevellec/cassandra-unit-examples.git and raising the cassandra-unit-spring dependency to 2.0.2.2.

A single run of SpringCQLScriptLoadTest.should_have_started_and_execute_cql_script() already creates about 2900+ lines of console output. 

All org.apache.cassandra stuff should be muted down to ERROR output, but obviously there are some unwanted entries as well.

14:09:04.357 [NonPeriodicTasks:1] DEBUG o.apache.cassandra.io.util.FileUtils - Deleting system-schema_columnfamilies-ka-493-Filter.db
14:09:04.357 [SharedPool-Worker-31] DEBUG o.apache.cassandra.transport.Message - Responding: ROWS [keyspace_name(system, schema_columnfamilies), org.apache.cassandra.db.marshal.UTF8Type][columnfamily_name(system, schema_columnfamilies), org.apache.cassandra.db.marshal.UTF8Type][bloom_filter_fp_chance(system, schema_columnfamilies), org.apache.cassandra.db.marshal.DoubleType][caching(system, schema_columnfamilies), org.apache.cassandra.db.marshal.UTF8Type][cf_id(system, 

I don't need a fix/release, but any kind of (dirty) workaround would be highly appreciated - just to speed up our build and be gentle with our build server.  :)

P.S.: Not sure if this can be considered an actual bug, but its a change of behavior, at least...

**Comment by MALPI** [comment]
Close this pls
