### ISSUE TITLE
Using a forked process?

### ISSUE THREAD

**Issue by burtonator** [jsevellec/cassandra-unit#107]
I'm dealing with dependency hell trying to get Apache Spark and Cassandra Unit working together.

Long story short, it's a mess.  There are like 6-7 conflicting libs.  Apache Spark works well by itself, and so does Cassandra Unit.. but together, they're a mess.

Has any work been done to try to get Cassandra Unit working as a forked process? This way the tests and cassandra don't have to have the same dependencies.

**Comment by OrangeDog** [comment]
That would also solve the conflicts between cassandra-all and cassandra-driver-core caused by metrics-core having changed its groupid but not its package names.

**Comment by Sandmania** [comment]
I do have some terrible dependency issues to which a custom shaded cassandra-unit brings some relief, but the metrics-core is something that I haven't been able to fix yet. Cassandra maven plugin (https://github.com/mojohaus/cassandra-maven-plugin) might help us here, but is at the moment based on an old version of cassandra and cassandra-unit, and does not support CQL3 for instance.

**Comment by OrangeDog** [comment]
I made sure cassandra-unit was listed first, so its dependencies go on the classpath before those of the driver.
This seems to have worked.

Alternatively, you can fiddle about with dependency exclusions, but this required a lot more work to deal with differing scopes.

**Comment by OrangeDog** [comment]
A forked process would also allow communication with the server while the tests are suspended in a debugger.

**Comment by Sandmania** [comment]
I think I could give cassandra-maven-plugin a go when I get the chance. Upgrading to a newer cassandra-unit shouldn't be too difficult...
