### ISSUE TITLE
PermGen

### ISSUE THREAD

**Issue by mohitanchlia** [jsevellec/cassandra-unit#108]
Is there a way to pass PermGen space when starting the embedded server? I am facing a unique issue where I get out of memory perm gen space for some reason when I try to start another in memory database for my integration test. I see embedded server actually launches another VM

17:21:53.520 [pool-13-thread-1] INFO  o.a.c.service.CassandraDaemon - Hostname: US5C514F818ADF
17:21:53.521 [pool-13-thread-1] INFO  o.a.c.service.CassandraDaemon - JVM vendor/version: Java HotSpot(TM) 64-Bit Server VM/1.7.0_65
17:21:53.521 [pool-13-thread-1] INFO  o.a.c.service.CassandraDaemon - Heap size: 372244480/1888485376
17:21:53.521 [pool-13-thread-1] INFO  o.a.c.service.CassandraDaemon - Code Cache Non-heap memory: init = 2555904(2496K) used = 2006016(1959K) committed = 2555904(2496K) max = 50331648(49152K)
17:21:53.521 [pool-13-thread-1] INFO  o.a.c.service.CassandraDaemon - PS Eden Space Heap memory: init = 34078720(33280K) used = 267386880(261120K) committed = 267386880(261120K) max = 697827328(681472K)
17:21:53.521 [pool-13-thread-1] INFO  o.a.c.service.CassandraDaemon - PS Survivor Space Heap memory: init = 5242880(5120K) used = 16760952(16368K) committed = 16777216(16384K) max = 16777216(16384K)
17:21:53.531 [pool-13-thread-1] INFO  o.a.c.service.CassandraDaemon - PS Old Gen Heap memory: init = 88080384(86016K) used = 26464800(25844K) committed = 88080384(86016K) max = 1416101888(1382912K)
17:21:53.531 [pool-13-thread-1] INFO  o.a.c.service.CassandraDaemon - PS Perm Gen Non-heap memory: init = 22020096(21504K) used = 72197816(70505K) committed = 72351744(70656K) max = 85983232(83968K)
17:21:53.531 [po

**Comment by OrangeDog** [comment]
No, it doesn't start a new JVM, it's just logging the info from the JVM you've started it in.

**Comment by MALPI** [comment]
Can be closed.
