### ISSUE TITLE
CQLDataLoader does not understand CQL comments

### ISSUE THREAD

**Issue by mxk1235** [jsevellec/cassandra-unit#111]
I am playing around with examples, and trying to execute the following file.cql.

> // CREATE KEYSPACE mykeyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
> 
> CREATE TABLE mykeyspace.games (
>     gameid text PRIMARY KEY,
>     team text
> ) WITH COMPACT STORAGE;

and the following load code

>         CQLDataLoader cqlLoader = new CQLDataLoader(cluster.connect());
>         cqlLoader.load(new ClassPathCQLDataSet("file.cql", true, "mykeyspace"));

Note, that I commented out the CREATE KEYSPACE statement, in favor of passing keyspace name and keyspace autocreate flag to the CQLDataSet object.

However, this fails with this error.  It is because the cassandra driver is attempting to execute the query line which contains nothing but the comment.   I think perhaps, the CQLDataLoader should check for and skip such lines.

thanks in advance!

>com.datastax.driver.core.exceptions.SyntaxError: line 1:132 mismatched character '<EOF>' expecting set null
>	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:35) ~[cassandra-driver-core-2.1.4.jar:na]
>	at >com.datastax.driver.core.DefaultResultSetFuture.extractCauseFromExecutionException(DefaultResultSetFuture.java:289) ~[cassandra-driver-core-2.1.4.jar:na]
>	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:205) ~[cassandra-driver-core-2.1.4.jar:na]
>	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:52) ~[cassandra-driver-core-2.1.4.jar:na]
>	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:36) ~[cassandra-driver-core-2.1.4.jar:na]
>	at org.cassandraunit.CQLDataLoader.load(CQLDataLoader.java:36) ~[cassandra-unit-2.0.2.2.jar:na]

**Comment by jsevellec** [comment]
Hi!

Thanks for reporting that issue. I will have a look asap

**Comment by jsevellec** [comment]
fixed by #116
