### ISSUE TITLE
Embedded Cassandra starts up on port 9142 rather than 9042

### ISSUE THREAD

**Issue by jiteshvassa** [jsevellec/cassandra-unit#121]
From the Cassandra wiki (https://wiki.apache.org/cassandra/FAQ#ports):

"... 9042 for native protocol clients..."

cassandra-unit seems to start of port 9142 by default.  It would be nice to change this to 9042 so that things work out of the box.

**Comment by trejkaz** [comment]
OTOH, deliberately testing against a different port would catch bugs in apps which hardcode the port number...

**Comment by jsevellec** [comment]
It has been done for this reason and also to no disturb any other local default installation of cassandra running on the same machine

the issue #119 will also solve the problem
