### ISSUE TITLE
Does cassandra-unit support SSL connections?

### ISSUE THREAD

**Issue by magnusart** [jsevellec/cassandra-unit#126]
Hi

For the akka-persistence-cassandra I have added support for using SSL with the datastax driver. I also setup a unit test for SSL that I can not get to work. Do you have any examples of using cassandra-unit with SSL enabled for tests?

The client setup works when using a live server setup. The server setup looks correct. As far as I've seen the keystore and truststore are accessed correctly (as I get other exceptions if I change paths, passwords etc)

My test can be found here: 
https://github.com/krasserm/akka-persistence-cassandra/blob/master/src/test/scala/akka/persistence/cassandra/journal/CassandraSslSpec.scala

Exception is:

```

Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9142 (com.datastax.driver.core.ConnectionException: [/127.0.0.1:9142] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/127.0.0.1:9142] Error writing: Closed channel)))
```

Travis output when running test:
https://travis-ci.org/krasserm/akka-persistence-cassandra/jobs/65968468

**Comment by magnusart** [comment]
Hi, do you have any thoughts about above? This is still an issue for us.

**Comment by jsevellec** [comment]
Hi,

Sorry for the late answer. Unfortunately, I never tried cassandra-unit with SSL.

**Comment by magnusart** [comment]
Ok. Do you know any reason to why it would not work? Is the server started in the same way as with running it in production. With default ports and communication over tcp etc.

**Comment by jsevellec** [comment]
If you start cassandra-unit with default options, it's using this cassandra.yml conf : https://github.com/jsevellec/cassandra-unit/blob/master/cassandra-unit/src/main/resources/cu-cassandra.yaml

Have you got a version of your tests working ok without the ssl conf?

**Comment by magnusart** [comment]
Yes it works when I do not have the SSL configuration setup. I've also seen that the config does read the keystores (I had the wrong path at first). The client code works fine when connecting to real clusters.
