### ISSUE TITLE
Dos cassandra unit support CUSTOM INDEX?

### ISSUE THREAD

**Issue by ahll** [jsevellec/cassandra-unit#133]
Hi
   Now Cassandra allows to use external plugin such as Stratio’s Cassandra Lucene Index,  and I have tried following testing with cassandra unit:

"CREATE CUSTOM INDEX IF NOT EXISTS tags_index ON experiencehasbtagnndex (lucene) USING  \n"
            + "      'com.stratio.cassandra.lucene.Index' WITH OPTIONS = { \n "
            + "'refresh_seconds' :  '1', \n"
            + "'schema' : '{ "
            + "      fields : { id : {type : \"uuid\"},\n"
            + "      taglist : {type : \"text\", analyzer : \"english\"},\n"
            + "      time : {type : \"long\"}\n"
            + "      } "
            + "   }' \n"
            + "};\n";

then I got :

java.lang.RuntimeException: java.lang.ClassNotFoundException: com.stratio.cassandra.lucene.Index.

So I want to know if cassandra unit support CUSTOM INDEX. if yes,  how to add an external lib to cassandra unit.

**Comment by jsevellec** [comment]
Hi,

As soon as you've got the library in your classpath, it should work.

**Comment by ahll** [comment]
Hi,
  I put the dependency in the maven, and it works.
  Thanks and regards.

**Comment by ahll** [comment]
Hi,

 I found another problem that I can insert data with Cassandra Unit, but I cannot use specific query which coming from Stratio’s Cassandra Lucene Index.An example is that I cannot do following query with Cassandra Unit :

"SELECT * FROM  experiencehasbtagnndex WHERE lucene  = ' {query : {type:"contains", field:"taglist", values : ["a","b"]},filter : { type: "range", field:"time",upper:0
 , include_upper : false }} }'limit 100 ;"

 It could be caused by that the plugin has created their own index. The description in their document: 

   "The Lucene's index files will be stored in the same directories where the Cassandra's will be. The default data directory is /var/lib/cassandra/data, and each index is placed next to the SSTables of its indexed column family."

So is Cassandra Unit support it?

Thanks again and regards.

**Comment by jsevellec** [comment]
I think that you have to configure your plugin to create indexes in the same places as cassandra-unit creates working directory for cassandra

**Comment by tokyohans** [comment]
@jsevellec great work! 
@ahll I have tried exactly the same, put the lucene index plugin on the classpath but get a snakeyaml configuration exception "can't construct a java object for tag... cluster_name: 'Text Cluster'". Further stacktrace info points at InvocationTargetException -> NoSuchMethodError com.google.collect.Sets.newConcurrentHashSet(). Seems like this is related to google Guava dependency issue. Any idea how to fix this? Thanks a lot.

**Comment by ahll** [comment]
Hi
  I do not put the plugin in class-path, Instead of that, I put it in  the maven dependency, and follwoing is my configuration:
   
  <dependency>
            <groupId>com.stratio.cassandra</groupId>
            <artifactId>cassandra-lucene-index-plugin</artifactId>
            <version>2.1.6.2</version>
            <scope>test</scope> 
            <type>jar</type> 
        </dependency>
        <dependency>
            <groupId>org.easytesting</groupId>
            <artifactId>fest-assert-core</artifactId>
            <version>2.0M2</version>    
            <scope>test</scope> 
            <type>jar</type> 
        </dependency>   
        <dependency>
            <groupId>com.datastax.cassandra</groupId>
            <artifactId>cassandra-driver-core</artifactId>
            <version>2.1.4</version>
        </dependency>
        <dependency>
            <groupId>com.datastax.cassandra</groupId>
            <artifactId>cassandra-driver-mapping</artifactId>
            <version>2.1.4</version>
        </dependency>
        <dependency>
            <groupId>org.cassandraunit</groupId>
            <artifactId>cassandra-unit-spring</artifactId>
            <version>2.0.2.2</version>
            <scope>test</scope>
            <type>jar</type>
            <exclusions>
                <exclusion>
                    <artifactId>logback-classic</artifactId>
                    <groupId>ch.qos.logback</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>logback-core</artifactId>
                    <groupId>ch.qos.logback</groupId>
                </exclusion>
            </exclusions>
        </dependency>

Fanally, I changed my job,  and did not fixed that issues.
