### ISSUE TITLE
Update Cassandra to 2.2.0

### ISSUE THREAD

**Issue by cretz** [jsevellec/cassandra-unit#136]
The `cassandra-all` JAR is at 2.2.0 and there are some fixes (e.g. [CASSANDRA-8390](https://issues.apache.org/jira/browse/CASSANDRA-8390) that would help. I don't believe this can be done via a simple upgrade because there are some binary incompatibilities.

**Comment by Augi** [comment]
I prepared Pull Request almost one month ago so it will be hopefully accepted soon: https://github.com/jsevellec/cassandra-unit/pull/134

**Comment by jsevellec** [comment]
It's now available in master and will be part of the next release thanks to @Augi #134 #139
