### ISSUE TITLE
Allow CassandraUnitTestExecutionListener to use a random port

### ISSUE THREAD

**Issue by philwebb** [jsevellec/cassandra-unit#142]
It would be helpful if `CassandraUnitTestExecutionListener` could use a random port with `@EmbeddedCassandra(port=0)`. The actual port used could be found using `SocketUtils.findAvailableTcpPort` and made available as a Spring `Environment` property for the tests to pick up.

**Comment by jsevellec** [comment]
I think that waht you're looking for is already available (but, unfortunately, not documented) : https://github.com/jsevellec/cassandra-unit/pull/119

**Comment by philwebb** [comment]
Perfect, thanks! I was running an older release so I hadn't notice that update.
