### ISSUE TITLE
Incorrect CQLLexer

### ISSUE THREAD

**Issue by mNantern** [jsevellec/cassandra-unit#150]
Hi !

I have an issue with the SimpleCQLLexer: I want to insert a complex JSON string into Cassandra and I have the following error:

```
com.datastax.driver.core.exceptions.SyntaxError: line 0:-1 no viable alternative at input '<EOF>'
```

The issue can be reproduced with the following CQL (simplified) file:

``` sql
INSERT INTO test(data) VALUES ('"''test;"');
```

That file can be imported without issue in Cassandra but doesn't work with Cassandra Unit.

Thank you!

**Comment by jsevellec** [comment]
Hi,

Thanks for the reporting this. I'll have a look

**Comment by jimenefe** [comment]
Hello Jérémy. I hit the same bug. I have forked the project  and implemented a fix. Would be great if you could take a look and merge if you are happy with it

https://github.com/jimenefe/cassandra-unit/commit/6cde0f7502fa2d5496482e725d16ab8509ed960f

Cheers
FJ

**Comment by jsevellec** [comment]
Hi @jimenefe 

Cool!

It would be great if you can provide a PR.

Cheers,

Jérémy

**Comment by jimenefe** [comment]
done

**Comment by jsevellec** [comment]
thanks!

**Comment by mNantern** [comment]
@jsevellec Do you know when you will merge that PR and release a new version ?

Thanks !

**Comment by jsevellec** [comment]
I've just done the release. It should be available through maven central soon.

**Comment by jimenefe** [comment]
thanks!

FJ
