### ISSUE TITLE
Is support for 2.2.2 is released yet or when it is scheduled to release

### ISSUE THREAD

**Issue by ashishsoni** [jsevellec/cassandra-unit#152]

**Comment by jsevellec** [comment]
Hi,

There's already a quite stable snapshot of cassandra-unit supporting cassandra 2.2.2
(https://oss.sonatype.org/content/repositories/snapshots/)

I'm currently waiting for the release of the 2.2.0 of the java driver to go ahead with the cassandra-unit release.

**Comment by amichair** [comment]
I was wondering as well... good to know why we're waiting :-)

btw from what I gather there won't be any java driver 2.2 - the first driver to support Cassandra 2.2.x will be the 3.0.0 driver, which is currently in alpha 5 and is expected to be released sometime in December.

**Comment by Augi** [comment]
I also think that there won't be 2.2 driver. There is relatively fresh 2.1.9 that works well.

**Comment by depend** [comment]
per https://groups.google.com/a/lists.datastax.com/forum/m/#!topic/java-driver-user/Vu0cD0BguMc, it seems 2.2.x has been discontinued and 3.x will become the recommended version soon.

**Comment by jsevellec** [comment]
cassandra-unit 2.2.2.1 has been released
