### ISSUE TITLE
.

### ISSUE THREAD

**Issue by jarrod-ledrew-vgh** [jsevellec/cassandra-unit#157]

**Comment by MALPI** [comment]
Should be closed...

**Comment by jarrod-ledrew-vgh** [comment]
I have to apologize for this as I don't know how this happened. I certainly have no recollection of even looking at this project much less posting an empty comment. I was doing some work with Cassandra in December of last year but didn't look at unit testing. Again, sorry for wasting your time guys.

**Comment by jsevellec** [comment]
no problem!
