### ISSUE TITLE
NoSuchMethodError: com.datastax.driver.core.Cluster$Builder.addContactPoints

### ISSUE THREAD

**Issue by jamesoliverband** [jsevellec/cassandra-unit#159]
I am getting the following error 

java.lang.NoSuchMethodError: com.datastax.driver.core.Cluster$Builder.addContactPoints(Ljava/lang/String;)Lcom/datastax/driver/core/Cluster$Builder;
    at org.cassandraunit.spring.AbstractCassandraUnitTestExecutionListener.startServer(AbstractCassandraUnitTestExecutionListener.java:63)

My UnitTest looks like this:

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = Application.class)
@TestExecutionListeners({ CassandraUnitTestExecutionListener.class })
@CassandraDataSet(value = "xxx.cql", keyspace = "xxx")
@EmbeddedCassandra(timeout = 30000L)
public class SomeTest {
    private static final String KEYSPACE = "xxx";

```
@Autowired
public SomeService someService;

@Test
public void should_have_started_and_execute_cql_script() throws Exception {
      someService.insert(....);
}
```

}

EDIT: my gradle dependencies look like this:
dependencies {
    compile("org.springframework.boot:spring-boot-starter:$springBootVersion")
    compile("org.springframework.data:spring-data-cassandra:1.3.2.RELEASE")
    compile("org.yaml:snakeyaml:1.15")
    compile("org.hsqldb:hsqldb:2.3.1")
    compile("org.projectlombok:lombok:1.16.2")
    testCompile('org.springframework:spring-test:4.2.4.RELEASE')
    testCompile("org.springframework.boot:spring-boot-starter-test:$springBootVersion")
    testCompile("junit:junit:4.11")
    testCompile 'org.cassandraunit:cassandra-unit-spring:2.2.2.1'
}

**Comment by dmitry-vasilyuk** [comment]
I have the same exception as described above.

My configuration:

Java test class contains the following annotations:

@RunWith(SpringJUnit4ClassRunner.class)
@TestExecutionListeners({DependencyInjectionTestExecutionListener.class})
@TestExecutionListeners({CassandraUnitDependencyInjectionIntegrationTestExecutionListener.class, DependencyInjectionTestExecutionListener.class})
@CassandraDataSet(value = {"cql/create_keyspaces.cql", "cql/create_tables.cql"})
@ContextConfiguration(classes = {CqlTemplateConfiguration.class}, loader = AnnotationConfigContextLoader.class)
@EmbeddedCassandra(timeout = 30000L)

pom.xml contains the following dependencies:
```
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-cassandra</artifactId>
    <version>1.3.2.RELEASE</version>
    <exclusions>
      <exclusion>
        <groupId>org.cassandraunit</groupId>
          <artifactId>cassandra-unit</artifactId>
      </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.cassandraunit</groupId>
    <artifactId>cassandra-unit-spring</artifactId>
    <version>2.2.2.1</version>
</dependency>
```

**Comment by jamesoliverband** [comment]
did you manage to solve the problem? For me it still not works.

**Comment by atemerev** [comment]
Confirming — same problem here. Cassandra 3.2.1

**Comment by miguelangcosta** [comment]
Is any solution for this issue?

**Comment by ffissore** [comment]
With #177 you can use latest cassandra-unit and exclude maven packages so to test against cassandra 2.2 while still using driver version 3

**Comment by jsevellec** [comment]
Closing the issue as the topic is outdated
