### ISSUE TITLE
New version based on cassandra 3.0.x ?

### ISSUE THREAD

**Issue by jsebrien** [jsevellec/cassandra-unit#166]
Hello,

Is it possible to release a new version based on cassandra 3.0.x?

Regards,

Julien

**Comment by eshepelyuk** [comment]
We're also interesting in this, We end up in using custom hacked version with disabled tests, although it does the job

**Comment by MALPI** [comment]
+1 Currently cassandraunit is not usable for us at all.

**Comment by nilsonfreitas** [comment]
Support for cassandra 3.0 would be great!

**Comment by MALPI** [comment]
Is actually anyone working on this? Probably #168 is related to that?

**Comment by jsevellec** [comment]
yes it's totally related. I'm about to integrate the PR #168 to master to release it

**Comment by MALPI** [comment]
any ETA on this?

**Comment by jsevellec** [comment]
I'll try to do that this week

**Comment by aeons** [comment]
Any ETA on release of a version with 3.0 support?

**Comment by jsevellec** [comment]
I've just done the release. The artifacts have been published to maven central. It should be available soon.

**Comment by busbey** [comment]
Yay! Thanks a bunch for this, it really helps out the YCSB project.

**Comment by MALPI** [comment]
Is this solved?

**Comment by jsevellec** [comment]
the release has been done, yeah.
