### ISSUE TITLE
Is it possible to release 2.2.2 version for cassandra-driver-core 3.0.0?

### ISSUE THREAD

**Issue by sedovalx** [jsevellec/cassandra-unit#173]
Unfortunetly the cassandra-unit-spring module should be rebuilt for it. I believe the https://github.com/jsevellec/cassandra-unit/issues/159 issue is related to this.

**Comment by ffissore** [comment]
With #177 you can use latest cassandra-unit and exclude maven packages so to test against cassandra 2.2
