### ISSUE TITLE
The hints_directory setting is missing from cu-cassandra-rndport.yaml

### ISSUE THREAD

**Issue by cmayes** [jsevellec/cassandra-unit#176]
Upon upgrade to Cassandra 3, I would get this error:

```
hints_directory is missing and -Dcassandra.storagedir is not set
```

I noticed that `cu-cassandra.yaml` had this line:

```
hints_directory: target/embeddedCassandra/hints
```

...but `cu-cassandra-rndport.yaml` did not.  I've made a project-local version of this config file with the line from `cu-cassandra.yaml`, which has gotten rid of the error.

**Comment by adamdougal** [comment]
Hi @jsevellec will there be a release soon containing this fix? Thanks!

**Comment by jsevellec** [comment]
I wanted to wait a bit before release a new version.

Anyway you've got several workarounds available : 
- there's a snapshot of cassandra-unit containing last commits (available here : https://oss.sonatype.org/content/repositories/snapshots/)
- you can use your own cassandra file 

Let me know if it's ok
