### ISSUE TITLE
Very high cpu load on Windows machines 

### ISSUE THREAD

**Issue by Jobs92** [jsevellec/cassandra-unit#179]
Hi,

I use cassandra-unit for unit testing. Running cassandra-unit on Linux works fine but if I use Windows (which is my preferred operating system) cassandra-unit has a cpu usage of 99%. I tried it on multiple machines and all show the same behavior on Windows. The system get's so slow that I can't continue to work. Is this a general issue with cassandra-unit and are there any fixes/ workarounds? (I use cassandra-unit 3.0.0.1)

**Comment by aeons** [comment]
I have the same issue on Mac OS X. Both for me and several of my colleagues.

**Comment by kbalyasnikov** [comment]
Same here on Mac OS X. All cores are busy...

**Comment by NoOrdInaryGuy** [comment]
I've also reproduced this issue on OSX.

It seems there is a workaround, though it's not ideal: Manually import `cassandra-all` version `3.6`, and exclude `cassandra-all` from the `cassandra-unit` dependency. i.e.:

```
"org.cassandraunit" % "cassandra-unit" % "3.0.0.1" exclude("org.apache.cassandra", "cassandra-all"),
"org.apache.cassandra" % "cassandra-all" % "3.6",
```

Versions of `cassandra-all` up to and including `3.5` exhibit the issue, `3.6` seems to fix it. A quick look at the Cassandra changelog doesn't give any obvious changes, except perhaps a new version of netty.

Attaching a profiler to the 'hung' JVM shows all of the CPU time is being spent in `org.apache.cassandra.concurrent.SEPWorker.run()` - and this isn't the case if using the workaround.

**Comment by aludwiko** [comment]
I have the same problem on Linux machine and proposed workaround is not helping. I notice that high cpu usage starts just after finishing the first `Spec`. I'm using akka-persitence and after all tests is spec I'm invoking:
```
TestKit.shutdownActorSystem(system, 30.seconds, verifySystemShutdown = false)
```
not sure if this is related to the problem.

When I switched back to version  `"org.cassandraunit" % "cassandra-unit" % "2.2.2.1"` problem disappear.

**Comment by marcuscbey** [comment]
Has anybody found a definitive reason this is happening? I'm seeing the same thing on cassandra-unit 2.1.9.

**Comment by jsevellec** [comment]
The issue looks to be linked to specific version of cassandra which started in embedded mode where causing the issue. The new version of cassandra-unit (3.1.1.0) is linked to cassandra-all in version 3.9 that looks to also fix the issue.

**Comment by marcuscbey** [comment]
We currently deploy against Cassandra 2.1.x so I was trying to avoid upgrading to cassandra-unit 3.x to ensure our tests are actually running against our deployed cassandra version. Do you have any idea what version of cassandra-all this started in? I could try rolling back that dependency

**Comment by pythonmax** [comment]
I'm using cassandra-unit 3.1.1.0 and I'm able to reproduce this issue on my Ubuntu 16.04.

**Comment by pythonmax** [comment]
I've found that problem was in multiple netty versions. I'm using cassandra-driver-core 3.1.2 which comes with netty 4.0.37.Final. But cassandra-unit 3.1.1.0 declares explicitly in dependencies netty 4.0.27.Final.

The workaround is to exclude netty from cassandra-unit:
```
        <dependency>
            <groupId>org.cassandraunit</groupId>
            <artifactId>cassandra-unit</artifactId>
            <version>3.1.1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-handler</artifactId>
                </exclusion>
            </exclusions>
            <scope>test</scope>
        </dependency>
```

So cassandra driver's netty will be used and CPU usage is back to normal after running tests.
I'm not sure but seems this can be fixed by adding `<optional>true</optional>` to `netty-handler` dependency in cassandra-unit/pom.xml.
