### ISSUE TITLE
NoSuchMethodError with Cassandra 3.9

### ISSUE THREAD

**Issue by amichair** [jsevellec/cassandra-unit#192]
Getting the exception below using cassandra-unit 3.0.0.1 and Cassandra 3.9. Apparently CommitLog.getContext() has been removed somewhere along the way, and cassandra-unit was not updated with the change.

btw, this kind of thing has happened at least a couple times before... perhaps you should have some unit tests run whenever a new version of Cassandra is released, so you'll pick up such breaking changes and fix them early on.

> java.lang.NoSuchMethodError: org.apache.cassandra.db.commitlog.CommitLog.getContext()Lorg/apache/cassandra/db/commitlog/ReplayPosition;
>         at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanupAndLeaveDirs(EmbeddedCassandraServerHelper.java:312)
>         at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:118)
>         at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:87)
>         at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:66)
>         at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:58)
>         at org.cassandraunit.utils.EmbeddedCassandraServerHelper.startEmbeddedCassandra(EmbeddedCassandraServerHelper.java:54)
> ...

**Comment by amichair** [comment]
Looks like this error occurs on 3.8 as well but 3.7 is ok - it was introduced in between them.

**Comment by geekbeast** [comment]
Does this still repro?

**Comment by amichair** [comment]
I believe it was fixed when cassandra-unit added support for 3.9.

**Comment by DavidRG13** [comment]
@amichair could you please confirm if this has been fixed? If so, could you please close this issue?

Thank you!
