### ISSUE TITLE
Default to Random Port Configuration

### ISSUE THREAD

**Issue by kevinconaway** [jsevellec/cassandra-unit#197]
@jsevellec does it make sense for @EmbeddedCassandra to default to using the random port `CASSANDRA_RNDPORT_YML_FILE` configuration instead of the default?

Not using a random port usually results in an unpleasant and non-deterministic test failure when running in a CI environment where there may be port conflicts for 9142.

**Comment by jsevellec** [comment]
It's a good question. The good thing is that it's available ;-)

**Comment by geekbeast** [comment]
👍

**Comment by kporowski** [comment]
👍

**Comment by jsevellec** [comment]
Closing the issue as the topic is outdated
