### ISSUE TITLE
Support shaded version for 3.1.1.0

### ISSUE THREAD

**Issue by barkhakeni** [jsevellec/cassandra-unit#199]
Currently the shaded version is 2.1.9.2 which supports older version of Cassandra. Can we have shaded version of cassandra-unit which supports 3.7+ version of cassandra. Shaded version of cassandra unit doesnt have system_schemas keyspaces which are in the later version of cassandra.

**Comment by trecloux** [comment]
The shaded jar identity is now :
```
        <dependency>
            <groupId>org.cassandraunit</groupId>
            <artifactId>cassandra-unit</artifactId>
            <version>3.1.1.0</version>
            <classifier>shaded</classifier>
        </dependency>
```

**Comment by barkhakeni** [comment]
@trecloux Thanks for the fast response. After adding this, our build is running very slow. Is it because of some conflict with netty?

**Comment by jsevellec** [comment]
linked to #200
