### ISSUE TITLE
Shaded artifact shouldn't be a derived classifier of main one

### ISSUE THREAD

**Issue by slandelle** [jsevellec/cassandra-unit#200]
Hey Ch'ti Jug guys!

IMHO, the current shaded artifact is really cumbersome to use.

The problem is that it's deployed as an alternate classifier of the main artifact, meaning that it doesn't have its own pom.xml.
As a consequence, when depending on the shaded artifact, one has to exclude `cassandra-all` that's being fetched from the non-shaded pom, and re-import all the dependencies that were not shaded into the jar, one by one.

It would be way better if the shaded artifact was a dedicated module that would depend on the main one, and that would deploy the modified shaded pom, hence with its actual dependencies.

Cheers!

**Comment by jsevellec** [comment]
Fair enough...

**Comment by slandelle** [comment]
PR sent, see #201

**Comment by jsevellec** [comment]
fast contribution... thanks!

**Comment by slandelle** [comment]
Well, that's just how things should work in open-source :)

**Comment by slandelle** [comment]
Thanks for merging!
Any idea of the ETA of the next release shipping this change? I'm not in a hurry, just to keep things on my radar.

**Comment by jsevellec** [comment]
No idea. Usually i'm waiting a bit to get a bunch of fix into a new one but i could do also do it quickly because the fix is already an interesting one. 

anyway, there's already a snapshot available (https://oss.sonatype.org/content/repositories/snapshots/)

**Comment by slandelle** [comment]
Well, you usually release twice or 3 times a year. I can wait weeks, but I have to admit I'd rather not depend on a snapshot dependency for months :)

**Comment by jsevellec** [comment]
message received ;-)

**Comment by slandelle** [comment]
Thanks man :)

**Comment by slandelle** [comment]
@jsevellec Gentle ping :) Do you have an ETA for the next release, please?

**Comment by jsevellec** [comment]
oh man. I thought i did it... I'll do it next week.

Sorry for that.

**Comment by slandelle** [comment]
Great, thanks!

**Comment by slandelle** [comment]
@jsevellec I see the `3.1.3.0` release commits in the git history, but it seems [it didn't make it to maven central](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.cassandraunit%22%20AND%20a%3A%22cassandra-unit%22) 😢

**Comment by jsevellec** [comment]
Yes, I'm facing issues when publishing to maven central but I'm on it

**Comment by slandelle** [comment]
Please let me know if I can help :)

**Comment by jsevellec** [comment]
released! (3.1.3.2) It should be available soon in Maven central

**Comment by slandelle** [comment]
Awesome, thanks a lot! Upgrade time!
