### ISSUE TITLE
After switching to cassandra-unit 3.1.1.0 it no longer works on Java 7 runtime environment

### ISSUE THREAD

**Issue by beastie1891** [jsevellec/cassandra-unit#205]
At this point we cannot switch to Java 8 but still want the latest version of cassandra-unit as it seem to have fixed issue: https://github.com/jsevellec/cassandra-unit/issues/110

Would it be possible that the latest version of cassandra-unit is build with Java 7 target environment?
I am getting Unspported Major Minor version 52.0 exception

**Comment by jsevellec** [comment]
The problem is that Cassandra 3 now requires java 8 to be able to start.

**Comment by beastie1891** [comment]
Yeah. I noticed. Okay. I guess we will be moving to Java 8
