### ISSUE TITLE
How to use it with an existing cassandra cluster

### ISSUE THREAD

**Issue by chjhaijiang** [jsevellec/cassandra-unit#209]
Hi,
How Can I use it with an existing cassandra cluster and run the basic unit test to verify the cluster is functioned well?
Basical, I don't want to start an embedded cassandra server

Thanks,
Haijiang

**Comment by fmatar** [comment]
You do not need to use it with an existing cluster, simply connect to your cluster with before and close the connection with after methods and you're good to go

**Comment by chjhaijiang** [comment]
OK, thanks. Make sense to me.

**Comment by diegokuh** [comment]
But for spring integration es mandatory to use the embedded cassandra right?
