### ISSUE TITLE
Timed out waiting for server response on vm environment

### ISSUE THREAD

**Issue by itstata** [jsevellec/cassandra-unit#210]
Hi,

i have proplems running cassandra unit on our vm environment. I'm running the test locally without any problem, but on the VM environment i'm getting timeouts for every test. 

Therefor i increased the timeout to 60 seconds. I'm confused, because the timeout aborts the test after 12,xx seconds.  Any ideas?

```
 @Rule
public CassandraCQLUnit cassandraCQLUnit = new CassandraCQLUnit(new ClassPathCQLDataSet(Constants.CREATE_SCRIPT, Constants.TEST_KEYSPACE),
            Constants.EMBEDDED_DEFAULT_CASSANDRA_YML_FILE, 60000L, 60000 );`
```

> 2017-01-03 08:50:49,420  WARN DatabaseDescriptor:563 - Small commitlog volume detected at target/embeddedCassandra/commitlog; setting commitlog_total_space_in_mb to 5031.  You can override this in cassandra.yaml
> 2017-01-03 08:50:49,428  WARN DatabaseDescriptor:590 - Small cdc volume detected at target/embeddedCassandra/cdc; setting cdc_total_space_in_mb to 2515.  You can override this in cassandra.yaml
> 2017-01-03 08:50:49,434  WARN DatabaseDescriptor:643 - Only 17.645GiB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
> 2017-01-03 08:50:49,435  WARN DatabaseDescriptor:764 - Please rename encryption_options as server_encryption_options in the yaml
> 2017-01-03 08:50:50,090  WARN CLibrary:163 - Unable to lock JVM memory (ENOMEM). This can result in part of the JVM being swapped out, especially with mmapped I/O enabled. Increase RLIMIT_MEMLOCK or run Cassandra as root.
> 2017-01-03 08:50:50,091  WARN StartupChecks:123 - jemalloc shared library could not be preloaded to speed up memory allocations
> 2017-01-03 08:50:50,091  WARN StartupChecks:156 - JMX is not enabled to receive remote connections. Please see cassandra-env.sh for more info.
> 2017-01-03 08:50:50,092 ERROR StartupChecks:159 - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
> 2017-01-03 08:50:57,342  WARN SystemKeyspace:1063 - No host ID found, created e0827f08-3cc1-4780-be19-0abc48ff428a (Note: This should happen exactly once per node).
> 2017-01-03 08:50:57,655  WARN StorageService:951 - Generated random token [-33089377447921533]. Random tokens will result in an unbalanced ring; see http://wiki.apache.org/cassandra/Operations
> 2017-01-03 08:51:03,010  WARN CompressionParams:382 - The sstable_compression option has been deprecated. You should use class instead
> 2017-01-03 08:51:10,698  WARN FBUtilities:338 - Trigger directory doesn't exist, please create it and try again.
> Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 40.713 sec
> Running dao.MeterStorageDataHistoryDaoImplTest
> Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 36.632 sec <<< FAILURE!
> testGetLatestRevisionHash(dao.MeterStorageDataHistoryDaoImplTest)  Time elapsed: 12.14 sec  <<< ERROR!
> com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1:9142] Timed out waiting for server response
> 	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:44)
> 	at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:26)
> 	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
> 	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
> 	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
> 	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43)
> 	at org.cassandraunit.CQLDataLoader.initKeyspaceContext(CQLDataLoader.java:59)
> 	at org.cassandraunit.CQLDataLoader.load(CQLDataLoader.java:31)
> 	at org.cassandraunit.CassandraCQLUnit.load(CassandraCQLUnit.java:63)
> 	at org.cassandraunit.BaseCassandraUnit.before(BaseCassandraUnit.java:35)
> 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
> 	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:86)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:241)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:87)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
> 	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:180)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
> 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
> 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
> **Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1:9142] Timed out waiting for server response**
> 	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:770)
> 	at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1374)
> 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:581)
> 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:655)
> 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:367)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
> 	at 
> 
> java.lang.Thread.run(Thread.java:745)

I'm also using a custom yaml file with increased timeouts .

> request_timeout_in_ms: 20000

The [BaseCassandraUnit](https://github.com/jsevellec/cassandra-unit/blob/master/cassandra-unit/src/main/java/org/cassandraunit/BaseCassandraUnit.java) has the method getSocketOptions() which is never called in my example.  Maybe that's the reason.
```
protected SocketOptions getSocketOptions() {
        SocketOptions socketOptions = new SocketOptions();
        socketOptions.setReadTimeoutMillis(this.readTimeoutMillis);
        return socketOptions;
    }
```
This looks like dead code for me:
https://github.com/jsevellec/cassandra-unit/search?utf8=%E2%9C%93&q=getSocketOptions

In [EmbeddedCassandraServerHelper ](https://github.com/jsevellec/cassandra-unit/blob/master/cassandra-unit/src/main/java/org/cassandraunit/utils/EmbeddedCassandraServerHelper.java) the timeout shoud be used for the cluster initialization (see [datastax documentation](http://docs.datastax.com/en/developer/java-driver/3.1/manual/socket_options/)). 

`cluster = Cluster.builder().addContactPoints(new String[]{getHost()}).withPort(getNativeTransportPort()).build();`

**Comment by itstata** [comment]
Now i'm using a workaround to set the timeout before each unit test:
```
  @Before
    public void initialize() {
        EmbeddedCassandraServerHelper.getCluster().getConfiguration().getSocketOptions().setReadTimeoutMillis(Constants.EMBEDDED_TIME_OUT);
    }
```

**Comment by jsevellec** [comment]
deprecated since the upgrade to the 4.2.2 of the cassandra java driver
