### ISSUE TITLE
stop using FutureFallback; no longer in Guava 20

### ISSUE THREAD

**Issue by kilobyte1024** [jsevellec/cassandra-unit#211]
Cassandraunit is compiled against some deprecated Guava code. This code was deprecated in Guava 19 and removed in Guava 20. Thus users of Cassandraunit can't upgrade to recent versions of Guava. Please patch to use the new Guava APIs (which have been available since Guava 18).

`FutureFallback` [is deprecated](https://google.github.io/guava/releases/19.0/api/docs/com/google/common/util/concurrent/FutureFallback.html) & should be replaced with `Futures.withFallback or AsyncFunction`.

This is the compiler error when running against Guava 21:
```
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
	at com.*.DaoTest.startupCassandra(DaoTest.java:41)
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.FutureFallback
	at com.*.DaoTest.startupCassandra(DaoTest.java:41)

```

**Comment by geekbeast** [comment]
Not sure about the server, but the official driver hasn't caught up yet. https://datastax-oss.atlassian.net/browse/JAVA-1328

Between Spark & Cassandra, it's going to be a while before a lot of folks can move on to 20.

**Comment by glindste** [comment]
Driver version 3.2.0 now uses guava 20

**Comment by DavidRG13** [comment]
Just realized this issue was here... my bad..

I duplicated it https://github.com/jsevellec/cassandra-unit/issues/233 and submit a PR:
https://github.com/jsevellec/cassandra-unit/pull/234

**Comment by DavidRG13** [comment]
@jsevellec  probably this could be closed

**Comment by kilobyte1024** [comment]
Agreed
