### ISSUE TITLE
Cassandra-unit with materialized views

### ISSUE THREAD

**Issue by dorheini** [jsevellec/cassandra-unit#213]
Hi.
Creating materialized views doesn't work when using embedded server with cassandra unit...
Is this currently not supported?
If the answer is no, is it going to be supported and when?

Thanks,

**Comment by selimnairb** [comment]
Hello,

I am also trying to use a materialized view with Cassandra-unit, and am getting this error:

`no viable alternative at input 'MATERIALIZED' ([CREATE] MATERIALIZED...);`

when the "CREATE MATERIALIZED VIEW..." CQL statement, specified in `getStartupScripts()` of my CassandraConfiguration, is executed.  

Note that this same CQL statement is happily executed by Spring Data Cassandra (1.5.3) when my app is running outside of unit tests.

Any chance of fixing this?

Let me know how I can help.

Thanks,

Brian

**Comment by selimnairb** [comment]
@dorheini Did you ever figure this out?

**Comment by dorheini** [comment]
No. still looking for in-mem cassandra that supports Materialized views.

**Comment by DavidRG13** [comment]
Hello @dorheini and @selimnairb, 
did you try the latest version? It's working for me

Please let us know if this could be closed

**Comment by DavidRG13** [comment]
@jsevellec probably this issue could be closed

**Comment by jsevellec** [comment]
Closing the issue as the topic is outdated
