### ISSUE TITLE
How to kill the started embedded cassandra?

### ISSUE THREAD

**Issue by shankarshastri** [jsevellec/cassandra-unit#250]
Cassandra unit starts, but still I find port 7010 still in use, even after the end of the process?

**Comment by abalonperin** [comment]
A bit late to the party but have you tried:
```
  EmbeddedCassandraServerHelper.getSession().close()
  EmbeddedCassandraServerHelper.getCluster().close()
```
?

**Comment by jsevellec** [comment]
Embedded Cassandra is started once for the JVM. As long as the JVM is started the process is still there (for your unit tests...)
