### ISSUE TITLE
No data loader for json data any more after cassandra-unit 3.0 ?

### ISSUE THREAD

**Issue by jintaoguan** [jsevellec/cassandra-unit#251]
From the source code, I didn't see any DataLoader for json data. 
The only one there is CQLDataLoader. 
Does that mean there will be no json data support?

**Comment by jsevellec** [comment]
Hi,

The json and xml dataset support was for the former Cassandra data model based on column family and is deprecated. The switch to CQL brought the new cassandra data model which is more table oriented. The new dataset supports for XML and JSON needs to be implemented so the dataset structure corresponds to the new cassandra data model.

I need also to update the wiki to remove it for the moment.
