### ISSUE TITLE
NPE when calling cleanEmbeddedCassandra

### ISSUE THREAD

**Issue by amichair** [jsevellec/cassandra-unit#278]
When upgrading from 3.3.0.2 to 3.5.0.1, my tests broke due to an NPE on shutdown. Seems it never initializes the cluster/session so fails to use them to drop the keyspaces. Worked ok in previous versions.

```
java.lang.NullPointerException
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.dropKeyspacesWithNativeDriver(EmbeddedCassandraServerHelper.java:285)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.dropKeyspaces(EmbeddedCassandraServerHelper.java:281)
	at org.cassandraunit.utils.EmbeddedCassandraServerHelper.cleanEmbeddedCassandra(EmbeddedCassandraServerHelper.java:193)
```

The workaround is to call

```
EmbeddedCassandraServerHelper.getSession();
```

to initialize the session/cluster, even though this session is not used anywhere in the tests, which is a bit weird. Would be nice if cassandra-unit took care of this internally so it would be safe to just call ```cleanEmbeddedCassandra``` on its own as it was before.

**Comment by hsn10** [comment]
yes, i noticed the same problem.

**Comment by jsevellec** [comment]
Having a look

**Comment by amichair** [comment]
The fix avoids the NPE, but it also doesn't perform the cleanup (it is simply skipped if the session is null). Perhaps it should actually get a session and do the cleanup? That's why cleanEmbeddedCassandra() was invoked, after all...

(btw it's possible this issue is a result of different users using cassandra-unit in different ways, which were not anticipated by the developers. Some might us getSession() and do with it stuff, and not encounter this issue. Others might just want to bring up the cassandra server instance, and connect to it using their own client code that creates sessions etc. and still want cleanup at the end. Just a thought, in case it helps...)
