### ISSUE TITLE
CompositeType for column values

### ISSUE THREAD

**Issue by rahja** [jsevellec/cassandra-unit#29]
Support for CompositeType in 'column values' is required.

cassandra-unit currently support composite types in "row key" and "column name". What I am looking for is composite type in 'column values'.

I think there should be an option to add "CompositeType" in "validationClass" and then a utility method something like composite(), on the same lines as utf8() to set values.

Following should be possible, after CompositeType is added.

<columnMetadata>
  <name>subject</name>
  <validationClass>CompositeType(UTF8Type,UTF8Type,UTF8Type)</validationClass>
  <indexType>KEYS</indexType>
</columnMetadata>

**Comment by jsevellec** [comment]
deprecated now
