### ISSUE TITLE
Versioning scheme is wrong

### ISSUE THREAD

**Issue by asarkar** [jsevellec/cassandra-unit#296]
Since SEMVAR sorts versions alphabetically, `3.7.1.0` is treated as newer to `3.11.2.0`. See [here](https://search.maven.org/search?q=g:org.cassandraunit%20AND%20a:cassandra-unit&core=gav).

One way to fix this problem is to use double digits for all numbers.

**Comment by jsevellec** [comment]
Yes I know i did a mistake with the versioning. 

I would advise to specify the version in the dependency to not take the last one

**Comment by asarkar** [comment]
What was done to resolve this issue?

**Comment by jsevellec** [comment]
Unfortunately nothing...
