### ISSUE TITLE
'key name' in data set

### ISSUE THREAD

**Issue by ghost** [jsevellec/cassandra-unit#57]
Is there a way to specify 'key name' in the data set?

The class I'm testing has a CQL 3 query like this:
SELECT my_key, my_column1 FROM table1 WHERE my_key = 'key1';
In my Cassandra unit test, I'm getting:
com.datastax.driver.core.exceptions.InvalidQueryException: Undefined name my_key in selection clause
  at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:32)
...

It seems because I didn't specify a key name in my data set. But I couldn't figure out how (with Cassandra unit).

I'm using Cassandra 1.2.2, datastax Java Driver 1.0.0-beta2, and Cassandra unit 1.1.2.1.

Thanks.

**Comment by jsevellec** [comment]
Closing the issue as the topic is outdated
