### ISSUE TITLE
@Autowired not working

### ISSUE THREAD

**Issue by kelouaaziza** [jsevellec/cassandra-unit#67]
Hi,

after adding @TestExecutionListeners({ CassandraUnitTestExecutionListener.class })
in JUnit test, the @Autowired does not work.

Thanks,
K.

**Comment by justinhrobbins** [comment]
The CassandraUnitDependencyInjectionTestExecutionListener really helped me with issues trying to use cassandra-unit-spring with an @Autoriwed Spring Data Cassandra bean.

@jsevellec may i suggest adding a reference to the CassandraUnitDependencyInjectionTestExecutionListener to the 'Spring for Cassandra unit' wiki page?

**Comment by jsevellec** [comment]
sure will do

**Comment by grubino** [comment]
This was really helpful.  I didn't see `CassandraUnitDependencyInjectionTestExecutionListener` on the wiki.  I would have found this much quicker if it were there.
