### ISSUE TITLE
EmbeddedCassandra : waiting 10 seconds may not be enough

### ISSUE THREAD

**Issue by jetoile** [jsevellec/cassandra-unit#77]
On old computer, when using a embeddedCassandra, waiting 10 seconds may not be enough before trying to load a cql script.

Indeed, in the class EmbeddedCassandraServerHelper (method startEmbeddedCassandra), a hard coded wait (startupLatch.await(10, SECONDS)) is done.
However when using a CQLDataLoader just after (manually or by spring annotations), a connection error occur.
Increasing this value to 30 seconds solves this issue.

Perhaps a retry policy could be applied.
What do you think about it?

Cheers.

Khanh

**Comment by Augi** [comment]
As #89 is merged, this issue can be closed, right?

**Comment by jetoile** [comment]
Hi,

Thx for the correction.
I think it should be ok.
