### ISSUE TITLE
Bug in CassandraUnitDepedencyInjectionTestExecutionListener ?

### ISSUE THREAD

**Issue by rsertelon** [jsevellec/cassandra-unit#96]
Hi,

For my tests, I have to use CassandraUnitDepedencyInjectionTestExecutionListener to benefit from Spring's dependency injection.

I've stumbled upon a problem. In my case, I use prepared statements, and inserts fail if they are not in the first executed test of my test class.

Indeed, these prepared statements are created once, on Spring context's creation. The TestExecutionListener provided in this case will reload the dataset for each method. Which obviously is not ideal when prepared statements are created just once for the entire test class (tables have different ids).

I've "fixed" this problem by modifying the TestExecutionListener to start Cassandra at beforeTestClass and not at prepareTestInstance. This ensures that the DB is started just once, and closed at the end of the test class.

I'm conscious that this changed the behavior of Cassandra Unit (with this TestExecutionListener) in that the dataset is kept for the test class whereas it was reset for each test method.

In my opinion this is still the good answer to this problem, as one should annotate a test method with `@DirtiesContext` if they want the dataset to be reset.

I'd like to create a pull request for this issue, but I was wondering if I should modify the existing TestExecutionListener or create a new one (and deprecate the old one?)

Thanks for your answer!

**Comment by HarvinderBhullar** [comment]
Hi

CassandraUnitDep... is great because it starts the embedded server first. My issue is when spring context is getting loaded it is connecting with my local cassandra server. How to make sure that autowired repository uses only embedded cassandra server.
Thanks

**Comment by rsertelon** [comment]
This is a configuration matter.

What I do is put the connection configuration in a properties file. When running tests, I simply give Spring another properties file with connection properties set to the embedded cassandra.

**Comment by HarvinderBhullar** [comment]
Thats what I am doing but it is loading the spring context before starting the embedded cassandra server.

**Comment by rsertelon** [comment]
Aaah so you have the same bug I was facing :)

I fixed that in a PR some times ago: https://github.com/jsevellec/cassandra-unit/pull/100

It's in master, but not released yet, is seems that @jsevellec cannot spend time on the project for now... ;)

**Comment by HarvinderBhullar** [comment]
Yes :) I am using released version waiting for the fixed to be released :)

**Comment by HarvinderBhullar** [comment]
It just seems to work when I did the following 

@TestExecutionListeners( {   CassandraUnitDependencyInjectionTestExecutionListener.class,DependencyInjectionTestExecutionListener.class })

I hope this is repeatable. (When I am putting DependencyInjection... first then i is failing)

**Comment by jsevellec** [comment]
I'll try to release it next week

**Comment by HarvinderBhullar** [comment]
Thanks jsevellec
